### ISSUE TITLE
Issue running auto script on Samsung Chromebook

### ISSUE THREAD

**Issue by Fedreg** [headmelted/code-builds#1]
This is a GREAT project!  Thanks for doing this!

I tried running the automated script and this is what I get :

` 
chronos@localhost / $  <( wget -O - https://code.headmelted.com/installers/chromebook.sh )
bash: /dev/fd/63: Permission denied
chronos@localhost / $ --2016-11-16 08:11:30--  https://code.headmelted.com/installers/chromebook.sh
Resolving code.headmelted.com... 104.27.186.80, 104.27.187.80
Connecting to code.headmelted.com|104.27.186.80|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3504 (3.4K) [text/plain]
Saving to: 'STDOUT'

-                                       0%[                                                                       ]       0  --.-KB/s    in 0s      

Cannot write to '-' (Success).`

...adding sudo and remoing the () also fail.

Am I missing something?  Haven't tried manual build yet but I can if it will help.

Thanks again!

**Comment by headmelted** [comment]
Can you just check that there is a period and a single space a the start of the line before pressing return?

You should see an ASCII art splash screen. Is that what comes up for you?

**Comment by headmelted** [comment]
If that doesn't work please also try wrapping the URL in double quotes..

**Comment by Fedreg** [comment]
it was the period, space.  Sorry I Missed that!   Running fine now; will let you know if there are any problems.   Thanks for the help!
