### ISSUE TITLE
arm64 supported? 

### ISSUE THREAD

**Issue by matthewsimo** [headmelted/code-builds#15]
Hi there, was giving this a whirl on my Samsung Chromebook Plus and ran into this error towards the end of the build. I was doing the scripted linux installation as I already had a xenial chroot set up. Any ideas? I'm not too familiar with Linux but I follow instructions well!  

```
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://dl.bintray.com/headmelted/deb-code-oss wheezy InRelease' doesn't support architecture 'arm64'
Done!
Installing Visual Studio Code...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package code-oss
Visual Studio Code install failed.
```

**Comment by headmelted** [comment]
Hi there,

Unfortunately arm64 is not supported, but only because Electron itself does
not support it fully (long story!).

HOWEVER, you might be able to use the armhf build just fine by entering the
chroot and doing this:

sudo apt-get install code-oss:armhf

Let me know how the above works for you on your machine (not having your
exact Chromebook in front of me means its a little guesswork).

**Comment by bkominik** [comment]
Hi, 

I'm running a xenial chroot, so I modified your install script. Here's the output:

$ sudo apt-get install code-oss:armhf
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package code-oss:armhf

**Comment by matthewsimo** [comment]
@headmelted Thanks for the response, I gave that a shot and got the same error as @bkominik 

```
E: Unable to locate package code-oss:armhf
```

**Comment by bkominik** [comment]
I was able to work around this issue installing a 32bit arm chroot. Once this installed the regular scripts work fine. There is a -a ARCH option in crouton. I did -a arm.

**Comment by headmelted** [comment]
Sorry, I missed a step above.

The chroot should not be necessary in this case, although is a viable option.

As ARMv8 is backwards compatible, the best solution is to:

**sudo dpkg --add-architecture armhf**

prior to executing the steps above.

For example:

**sudo dpkg --add-architecture armhf && sudo apt-get update && sudo apt-get install code-oss:armhf**

Let me know if this helps at all (hopefully it will!)

**Comment by bkominik** [comment]
That did work, thanks! much better to have a 64bit OS. The only additional
step I needed to do was install these packages: libxtst6:armhf
libasound2:armhf

**Comment by blinderjay** [comment]
**Unable to correct dependencies**
I'm so pleased that the code-oss have been installed in my chroot(ubuntu).However some dependencies seem to be wrong.
my computer is chromebook plus with aach architecture,

- firstly, i download the xenial with crouton;
- then, i enter chroot and typed `. <( wget -O - https://code.headmelted.com/installers/apt.sh )`;

- and, `sudo dpkg --add-architecture armhf && sudo apt-get update && sudo apt-get install code-oss:armhf`

- when finished intalling, i tried to load the code-oss,but failed,so i typeed `sudo dpkg --add-architecture armhf && sudo apt-get update && sudo apt-get install code-oss:armhf` again,

- finally:
```
......
 update-manager-core : Depends: python3:any (>= 3.2~)
                       Recommends: libpam-modules (>= 1.0.1-9ubuntu3) but it is not installed
 update-notifier:arm64 : Depends: update-notifier-common:arm64 (= 3.168.7) but it is not installable
                         Depends: update-manager-gnome:arm64 but it is not installable or
                                  update-manager:arm64 (>= 1:16.04.6) but it is not installable
                         Depends: ubuntu-release-upgrader-gtk:arm64 but it is not installable
                         Recommends: apport-gtk:arm64 (>= 2.8-0ubuntu3) but it is not installable
                         Recommends: software-properties-gtk:arm64 but it is not installable
                         Recommends: python3-aptdaemon:arm64 but it is not installable
 update-notifier-common : PreDepends: dpkg (>= 1.15.7.2) but it is not installed
                          Depends: python3:any
                          Depends: python3-apt but it is not installed
                          Depends: python3-dbus but it is not installed
                          Depends: patch but it is not installed
                          Recommends: libpam-modules (>= 1.0.1-9ubuntu3) but it is not installed
 xfonts-base : Depends: xfonts-utils (>= 1:7.5+2) but it is not installed
 xfonts-scalable : Depends: xfonts-utils but it is not installed
 xml-core : Depends: sed (>= 4.1.2-8) but it is not installed
 xorg:arm64 : Depends: xorg-docs-core:arm64 but it is not installable
 xserver-common : Depends: x11-xkb-utils but it is not installed
                  Recommends: xauth but it is not installed
 xserver-xorg-core:arm64 : Depends: keyboard-configuration:arm64 but it is not installable
 yelp:arm64 : Depends: yelp-xsl:arm64 (>= 3.12.0) but it is not installable
              Recommends: gnome-user-guide:arm64 but it is not installable
 zenity:arm64 : Depends: zenity-common:arm64 (= 3.18.1.1-1ubuntu2) but it is not installable
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
E: Unable to correct dependencies
```

**Comment by Rafcin** [comment]
@blinderjay did you ever resolve the issue with apt-get? I have the same issue now.

**Comment by digitalsanity** [comment]
The problem is dependencies in the newer packages on apt:armhf and ubuntu*:armhf that can break your arm64 installation by removing the arm64 versions.  Until those dependencies are corrected, installing an old package works to get started:

Step 1.

sudo dpkg --add-architecture armhf
sudo apt-get update

Step 2. 

Download e.g. (later versions may work, I used this though):
 https://bintray.com/headmelted/deb-code-oss/download_file?file_path=code-oss_1.10.0-201722210_armhf.deb

Step 3.

Use gdebi to install package and dependencies:

sudo apt-get install gdebi
sudo gdebi code*.deb

Step 4.

Install dependencies likely still missing from old package:
sudo apt-get install libxtst6:armhf
sudo apt-get install libasound2:armhf
