### ISSUE TITLE
No shell in crosh

### ISSUE THREAD

**Issue by phlebas** [headmelted/code-builds#2]
Following the instructions on an Asus C100PA Chromebook in developer mode I get as far as step 3:
crosh> shell
ERROR: unknown command: shell

The crouton extension is installed and active.

Any ideas?

Thanks

**Comment by headmelted** [comment]
Not sure if you got this working before you closed?

I *think* you maybe aren't in developer mode?

**Comment by phlebas** [comment]
On 16 November 2016 at 20:32, Jay Rodgers <notifications@github.com> wrote:

> Not sure if you got this working before you closed?
>
> I *think* you maybe aren't in developer mode?
>

Yeah, my mistake.

Tony
