### ISSUE TITLE
aarch64 chromebook support?

### ISSUE THREAD

**Issue by ericvh** [headmelted/code-builds#4]
Looks like armv7 support only on chromebooks, with the new Samsung Pro and Acer R13 it would be nice to have aarch64 support.

**Comment by headmelted** [comment]
I have looked into this, and wanted to deliver aarch64 builds along with the initial release.  I actually had a brief discussion with @code over twitter prior to the initial release to discuss the hurdles here.  I've adapted that comment below to explain the situation:

After tracing this through the codebase of three different projects it appears that libchromiumcontent, which is Electron's binary lib collection for Chromium, takes ARM to mean only the hard-float eabi 32-bit variant. This should in most cases be OK as ARM is backwards compatible from V7 on, but it's clearly not ideal.

This interpretation seems to have carried down to Electron and in turn Atom and VS code. So would need addressed in libchromiumcontent, then Electron, then VS code.

Its not insurmountable by any means, but I don't know when I'll find the time to start hacking at libchromiumcontent's build scripts to get that rolling.

The upside if someone gets that done is that it means you should be able to get all ARM, both PowerPC variants, and both MIPS variants for little extra effort while in there.

Certainly if someone wants to take this on I'd be more than happy to add aarch64 to these builds, but it would need those changes to libchromiumcontent and Electron first.

**Comment by smf723** [comment]
Do you know if there is any update on this? I have an Acer R13 and it would be nice to have aarch64 support.

**Comment by magic-k** [comment]
The arm64 version works on the R13. At least it does on mine.

**Comment by smf723** [comment]
Sorry, I should have updated this. Once I switched from the Dev channel to Beta it worked. I'm not sure if switching the channels made a difference or if simply the PowerWash resolved it.
