### ISSUE TITLE
amd64 link is not working

### ISSUE THREAD

**Issue by olijf** [headmelted/code-builds#6]
I wanted to test this build but the installer script did not seem to work, it reports something about wrong architecture.
I'm on debian amd64 so I tried the manual package install but the link is dead. Could you fix that for me?

**Comment by headmelted** [comment]
Hi,

It seems the automatic publish on Bintray failed.

The package has now been released manually and the links are working again.  Please let me know how this goes.

What's the make and model of your device so I can investigate at this side?

Thanks for letting me know about this.

**Comment by headmelted** [comment]
Will close for now as the link has been restored. Please let me know if this problem occurs again.

**Comment by olijf** [comment]
I finally got the time to try it again, but the only thing that I get is a black screen with a large squere inside it. Looks like it seems to be the same issue as https://github.com/headmelted/code-builds/issues/7 

Could you maybe help me out here?

**Comment by olijf** [comment]
Never mind, it looks like this is a code specific issue, with the official built it also happens
