### ISSUE TITLE
"1.8.0" build is out of date

### ISSUE THREAD

**Issue by ghost** [headmelted/code-builds#9]
It may be a mistake on my part to be reading the substring in
"1.8.0-2016112710" as a date, but according to the [release info from the
vscode project], vscode 1.8.0 is based on this commit:

https://github.com/Microsoft/vscode/commit/38746938a4ab94f2f57d9e1309c51fd6fb37553d

If the code-oss builds were made on 2016 November 27, that means that the OSS
1.8.0 build is missing two weeks of commits when compared to the VSCode team's
actual 1.8.0 release, or hundreds of changes.

[relase info from the vscode project]:
https://github.com/Microsoft/vscode/commit/38746938a4ab94f2f57d9e1309c51fd6fb37553d

**Comment by headmelted** [comment]
This version number is defined in code, and pulled from the upstream repo. It's likely that the version number that is used for package naming hadn't been bumped at that time and this carried over to these builds.

Currently the builds are reading 1.10.0. You are absolutely correct that the remaining digits are a datestamp of the build.
